### ISSUE TITLE
Bug while using xlotus in xorg

### ISSUE THREAD

**Issue by Besufikad17** [warrior0x7/xlotus#1]
Hey there, I followed the tutorial and the video post from [r/unixporn](https://www.reddit.com/r/unixporn/comments/1d78v0n/oc_fzf_youtube_rss_with_import_export_to_newpipe/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) and tries to add a feed using `xl-yt -a clip` command and I got this error.

```
Failed to connect to a Wayland server: No such file or directory
Note: WAYLAND_DISPLAY is unset (falling back to wayland-0)
Note: XDG_RUNTIME_DIR is set to /run/user/1000
Please check whether /run/user/1000/wayland-0 socket exists and is accessible.
```

Seems like it's trying to use Wayland service which isn't available in i3 xorg sessions. Does xlotus only supports Wayland or am I missing something? Thanks in advance

Current setup

- OS - Opensuse Tumbleweed
- WM - i3

**Comment by warrior0x7** [comment]
Sorry for that. it's my fault as I use RiverWM (wayland)

`xl-yt` uses `wl-clipboard`  which only works on wayland. I will install an xorg wm later today and fix the issue

**Comment by warrior0x7** [comment]
@Besufikad17 

I added support for Xorg clipboard using xclip 9ef411a5072fe209ede794d40a3c21a4abb70f75 and used the same condition to copying URL ec08eea4870b1c3bedc9861a284b82c772f5b71

I also separated dependency install in README

Would you mind trying it to see if it works?

**Comment by Besufikad17** [comment]
It works like a charm, Thanks again.
